/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatUIContent: typeof import('./components/ChatUI/Content/index.vue')['default']
    ChatUIHistory: typeof import('./components/ChatUI/History/index.vue')['default']
    ChatUILoading: typeof import('./components/ChatUI/Loading/index.vue')['default']
    ChatUINavbar: typeof import('./components/ChatUI/Navbar/index.vue')['default']
    ChatUISender: typeof import('./components/ChatUI/Sender/index.vue')['default']
    ChatUIThinking: typeof import('./components/ChatUI/Thinking/index.vue')['default']
    ChatUIThinkingIndicator: typeof import('./components/ChatUI/Thinking/indicator.vue')['default']
    ICUTabbar: typeof import('./components/ICU/Tabbar.vue')['default']
    MarkedParser: typeof import('./components/MarkedParser/index.vue')['default']
    SSEClient: typeof import('./components/SSEClient/index.vue')['default']
    SSEClientApp: typeof import('./components/SSEClient/app.vue')['default']
    SSEClientWechat: typeof import('./components/SSEClient/wechat.vue')['default']
  }
}
